services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    tty: true
    stdin_open: true
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3000
  database:
    image: mongo:6
    command: mongod --quiet
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_DB}
    ports:
      - '27017:27017'
    volumes:
      - motify:/data/db

volumes:
  motify:
